# Generated by Django 3.2.25 on 2025-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployed_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
