# Generated by Django 5.1.6 on 2025-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_deployed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
